import { readdirSync, readFileSync } from 'node:fs';
import { basename, join } from 'node:path';

const ROOT_PLACEHOLDER = '{{PRAGMA_ROOT}}';
const GENERATED_NOTE = '<!-- Generated by scripts/generate-copilot.js — edit the sources it reads, not this file. -->';

/**
 * Copilot loads skills as SKILL.md with name/description frontmatter, and
 * resolves no plugin-root variable inside the skill text (Claude Code
 * substitutes ${CLAUDE_PLUGIN_ROOT}; nothing in Copilot's docs says it does the
 * same). So the body says where the plugin root is in prose and leaves the
 * agent to resolve it — it knows where it read this file from.
 */
const ROOT_PREAMBLE = [
  '> **Plugin root.** `<plugin-root>` below means the directory this plugin is installed in —',
  '> three levels above this file (`<plugin-root>/copilot/skills/<skill>/SKILL.md`). Work it out from',
  "> this file's location before running anything. If you cannot tell where this file lives, look",
  '> under `~/.copilot/installed-plugins/` for the directory containing `principles/core.md`.',
].join('\n');

/**
 * Descriptions are the trigger text a host matches a request against, and they
 * already exist — written once for the Claude Code skills. Read them from there
 * rather than keeping a second copy that would drift.
 */
function descriptionOf(markdown) {
  const match = /^description:\s*(.+)$/m.exec(markdown);
  if (!match) throw new Error('No description in frontmatter');
  return match[1].trim();
}

function bodyAfterFrontmatter(markdown) {
  return markdown.replace(/^---\n[\s\S]*?\n---\n/, '').trim();
}

function yamlString(value) {
  return `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
}

function skillFile(name, description, template) {
  const [title, ...rest] = template.replaceAll(ROOT_PLACEHOLDER, '<plugin-root>').trim().split('\n');
  return [
    '---',
    `name: ${name}`,
    `description: ${yamlString(description)}`,
    '---',
    '',
    GENERATED_NOTE,
    '',
    title,
    '',
    ROOT_PREAMBLE,
    ...rest,
    '',
  ].join('\n');
}

/** relative path -> file content, for everything the Copilot plugin generates. */
export function buildCopilotFiles(root) {
  const templatesDir = join(root, 'templates', 'commands');
  const files = new Map();

  for (const fileName of readdirSync(templatesDir).sort()) {
    const name = basename(fileName, '.md'); // pragma-mode
    const claudeSkill = name.replace(/^pragma-/, ''); // mode
    const description = descriptionOf(readFileSync(join(root, 'skills', claudeSkill, 'SKILL.md'), 'utf8'));
    const template = readFileSync(join(templatesDir, fileName), 'utf8');
    files.set(`copilot/skills/${name}/SKILL.md`, skillFile(name, description, template));
  }

  const agent = readFileSync(join(root, 'agents', 'pragmatic-reviewer.md'), 'utf8');
  files.set('copilot/agents/pragmatic-reviewer.agent.md', [
    '---',
    'name: pragmatic-reviewer',
    `description: ${yamlString(descriptionOf(agent).replaceAll('/pragma:', 'pragma-'))}`,
    'tools: ["read", "search"]',
    '---',
    '',
    GENERATED_NOTE,
    '',
    bodyAfterFrontmatter(agent),
    '',
  ].join('\n'));

  return files;
}
