#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pluginRoot } from '../hooks/lib/paths.js';
import { describeUnderTarget, installTemplates, mergeHooksByCommand, substitutePaths } from './lib/install-helpers.js';

const SUPPORTED_HOOKS_VERSION = 1;
const CURSOR_DIR_NAME = '.cursor';
const HOOKS_FILE_NAME = 'hooks.json';

// resolve(), not join(): join() treats an absolute second argument as just
// another path segment to concatenate, rather than the anchor path.resolve()
// correctly makes it — passing an absolute target would silently nest it under
// the current directory instead of using it directly.
const target = process.argv[2] ? resolve(process.cwd(), process.argv[2]) : process.cwd();
const root = pluginRoot();
const cursorDir = join(target, CURSOR_DIR_NAME);
const templateDir = join(root, 'cursor');
// Command bodies are host-agnostic prose, shared with the Antigravity
// installer — kept out of cursor/ so that directory only names what's genuinely
// Cursor-specific.
const commandsSourceDir = join(root, 'templates', 'commands');

const report = [];

installRule();
installHooks();
installCommands();

process.stdout.write(`${report.join('\n')}\n`);

function installRule() {
  const dir = join(cursorDir, 'rules');
  mkdirSync(dir, { recursive: true });

  const ladder = readFileSync(join(root, 'principles', 'core.md'), 'utf8').trim();
  const file = join(dir, 'pragma.mdc');
  const content = [
    '---',
    'description: Pragmatic Programmer design ladder — how cheap this code is to change later.',
    'alwaysApply: true',
    '---',
    '',
    `<!-- Generated by pragma's install-cursor.js from principles/core.md.`,
    '     Re-run the installer after updating core.md rather than hand-editing this file. -->',
    '',
    ladder,
    '',
  ].join('\n');

  writeFileSync(file, content, 'utf8');
  report.push(`rule:     ${describeUnderTarget(file, target)}`);
}

function installHooks() {
  const file = join(cursorDir, HOOKS_FILE_NAME);
  const template = JSON.parse(readFileSync(join(templateDir, HOOKS_FILE_NAME), 'utf8'));
  const substituted = substitutePaths(template, root);

  const existing = readExistingHooks(file);
  if (existing === null) return; // unsupported version — readExistingHooks already reported why

  mergeHooksByCommand(existing.hooks, substituted.hooks);

  mkdirSync(cursorDir, { recursive: true });
  writeFileSync(file, `${JSON.stringify(existing, null, 2)}\n`, 'utf8');
  report.push(`hooks:    ${describeUnderTarget(file, target)} (sessionStart, afterFileEdit, postToolUse, stop)`);
}

function installCommands() {
  const commandNames = installTemplates(commandsSourceDir, join(cursorDir, 'commands'), root);
  report.push(`commands: ${commandNames.join(', ')}`);
}

/**
 * A missing file is the common case (first install). An existing file with a
 * hooks version this installer doesn't understand is left alone rather than
 * risked — merging into an unfamiliar schema is exactly the kind of guess this
 * plugin exists to catch elsewhere.
 */
function readExistingHooks(file) {
  if (!existsSync(file)) return { version: SUPPORTED_HOOKS_VERSION, hooks: {} };

  const parsed = JSON.parse(readFileSync(file, 'utf8'));
  if ((parsed.version ?? SUPPORTED_HOOKS_VERSION) !== SUPPORTED_HOOKS_VERSION) {
    report.push(`hooks:    left ${describeUnderTarget(file, target)} untouched — version ${parsed.version} is`
      + ` newer than this installer supports (${SUPPORTED_HOOKS_VERSION}). Add pragma's hooks`
      + ` from ${join(root, 'cursor', HOOKS_FILE_NAME)} by hand.`);
    return null;
  }
  parsed.hooks ??= {};
  return parsed;
}
