#!/usr/bin/env node
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join, resolve } from 'node:path';
import { pluginRoot } from '../hooks/lib/paths.js';

const SUPPORTED_HOOKS_VERSION = 1;
const CURSOR_DIR_NAME = '.cursor';
const HOOKS_FILE_NAME = 'hooks.json';

// resolve(), not join(): join() treats an absolute second argument as just
// another path segment to concatenate, rather than the anchor path.resolve()
// correctly makes it — passing an absolute target would silently nest it under
// the current directory instead of using it directly.
const target = process.argv[2] ? resolve(process.cwd(), process.argv[2]) : process.cwd();
const root = pluginRoot();
const cursorDir = join(target, CURSOR_DIR_NAME);
const templateDir = join(root, 'cursor');

const report = [];

installRule();
installHooks();
installCommands();

process.stdout.write(`${report.join('\n')}\n`);

function installRule() {
  const dir = join(cursorDir, 'rules');
  mkdirSync(dir, { recursive: true });

  const ladder = readFileSync(join(root, 'principles', 'core.md'), 'utf8').trim();
  const file = join(dir, 'pragma.mdc');
  const content = [
    '---',
    'description: Pragmatic Programmer design ladder — how cheap this code is to change later.',
    'alwaysApply: true',
    '---',
    '',
    `<!-- Generated by pragma's install-cursor.js from principles/core.md.`,
    '     Re-run the installer after updating core.md rather than hand-editing this file. -->',
    '',
    ladder,
    '',
  ].join('\n');

  writeFileSync(file, content, 'utf8');
  report.push(`rule:     ${describeUnderTarget(file)}`);
}

function installHooks() {
  const file = join(cursorDir, HOOKS_FILE_NAME);
  const template = JSON.parse(readFileSync(join(templateDir, HOOKS_FILE_NAME), 'utf8'));
  const substituted = substitutePaths(template);

  const existing = readExistingHooks(file);
  if (existing === null) return; // unsupported version — readExistingHooks already reported why

  for (const [event, entries] of Object.entries(substituted.hooks)) {
    existing.hooks[event] ??= [];
    for (const entry of entries) {
      const alreadyPresent = existing.hooks[event].some((e) => e.command === entry.command);
      if (!alreadyPresent) existing.hooks[event].push(entry);
    }
  }

  mkdirSync(cursorDir, { recursive: true });
  writeFileSync(file, `${JSON.stringify(existing, null, 2)}\n`, 'utf8');
  report.push(`hooks:    ${describeUnderTarget(file)} (sessionStart, afterFileEdit, postToolUse, stop)`);
}

function installCommands() {
  const sourceDir = join(templateDir, 'commands');
  const targetDir = join(cursorDir, 'commands');
  mkdirSync(targetDir, { recursive: true });

  const commandNames = readdirSync(sourceDir).map((name) => {
    const content = substitutePaths(readFileSync(join(sourceDir, name), 'utf8'));
    writeFileSync(join(targetDir, name), content, 'utf8');
    return `/${basename(name, '.md')}`;
  });

  report.push(`commands: ${commandNames.join(', ')}`);
}

/**
 * A missing file is the common case (first install). An existing file with a
 * hooks version this installer doesn't understand is left alone rather than
 * risked — merging into an unfamiliar schema is exactly the kind of guess this
 * plugin exists to catch elsewhere.
 */
function readExistingHooks(file) {
  if (!existsSync(file)) return { version: SUPPORTED_HOOKS_VERSION, hooks: {} };

  const parsed = JSON.parse(readFileSync(file, 'utf8'));
  if ((parsed.version ?? SUPPORTED_HOOKS_VERSION) !== SUPPORTED_HOOKS_VERSION) {
    report.push(`hooks:    left ${describeUnderTarget(file)} untouched — version ${parsed.version} is`
      + ` newer than this installer supports (${SUPPORTED_HOOKS_VERSION}). Add pragma's hooks`
      + ` from ${join(root, 'cursor', HOOKS_FILE_NAME)} by hand.`);
    return null;
  }
  parsed.hooks ??= {};
  return parsed;
}

function substitutePaths(value) {
  const source = typeof value === 'string' ? value : JSON.stringify(value);
  const replaced = source.replaceAll('{{PRAGMA_ROOT}}', root.replaceAll('\\', '/'));
  return typeof value === 'string' ? replaced : JSON.parse(replaced);
}

/** `file` is always an absolute path already built under `target` by this script. */
function describeUnderTarget(file) {
  return file.slice(target.length + 1).replaceAll('\\', '/');
}
